[package]
name = "unmoved-mover"
version = "0.1.0"
authors = ["Simon Strassl <simon@sigmoid.at>", "Maximilian Moser <maximilian.moser@tuwien.ac.at>"]
edition = "2018"


[dependencies]
log = "0.4.8"
env_logger = "0.7.1"
clap = "2.33.0"
swayipc = "3.0.0-alpha.3"