[package]
name = "unmoved-mover"
version = "0.1.0"
authors = ["Simon Strassl <simon@sigmoid.at>"]
edition = "2018"


[dependencies]
log = "0.4.8"
env_logger = "0.7.1"
clap = "2.33.0"
swayipc = "2.7.2"